app = 'shadowsoc-simulator'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[processes]
  worker = 'dotnet ShadowSOC.Simulator.dll'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
