services:
  # --- Infrastructure ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 15s
      timeout: 10s
      retries: 5

  # --- Backend Services ---
  api:
    build:
      context: .
      dockerfile: ShadowSOC.Api/Dockerfile
    ports:
      - "5174:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: ShadowSOC.Consumer/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy

  simulator:
    build:
      context: .
      dockerfile: ShadowSOC.Simulator/Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - AbuseIPDB__ApiKey=${ABUSEIPDB_API_KEY:-fallback}
    depends_on:
      kafka:
        condition: service_healthy

  # --- Frontend ---
  web:
    build:
      context: ShadowSOC.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
